---
- name: Deploy Celery units
  template:
    owner: root
    group: root
    mode: 0644
    src: galaxy-celery.service.j2
    dest: /etc/systemd/system/galaxy-celery.service
  notify: daemon reload

- name: Deploy Celery-beat units
  template:
    owner: root
    group: root
    mode: 0644
    src: galaxy-celery-beat.service.j2
    dest: /etc/systemd/system/galaxy-celery-beat.service
  notify: daemon reload

- name: Enable Celery
  systemd:
    name: "galaxy-celery.service"
    enabled: true
    state: started

- name: Enable Celery-beat
  systemd:
    name: "galaxy-celery-beat.service"
    enabled: true
    state: started
