---
- name: Deploy Celery-beat units
  template:
    owner: root
    group: root
    mode: 0644
    src: galaxy-celery-beat.service.j2
    dest: /etc/systemd/system/galaxy-celery-beat.service
  notify: daemon reload

- name: Enable Celery-beat
  systemd:
    name: "galaxy-celery-beat.service"
    enabled: true
    state: started

- name: Deploy without watchdog
  block:
    - name: Disable watchdog internal
      systemd:
        name: "galaxy-celery-dog-internal@{{ item }}.service"
        enabled: false
        state: stopped
      loop: "{{ range(0, galaxy_systemd_celery_internal_workers) | list }}"
      ignore_errors: true

    - name: Disable watchdog external
      systemd:
        name: "galaxy-celery-dog-external@{{ item }}.service"
        enabled: false
        state: stopped
      loop: "{{ range(0, galaxy_systemd_celery_external_workers) | list }}"
      ignore_errors: true

    - name: Deploy Celery units for internal queue
      template:
        owner: root
        group: root
        mode: 0644
        src: galaxy-celery-internal@.service.j2
        dest: /etc/systemd/system/galaxy-celery-internal@.service
      notify: daemon reload

    - name: Deploy Celery units for external queue
      template:
        owner: root
        group: root
        mode: 0644
        src: galaxy-celery-external@.service.j2
        dest: /etc/systemd/system/galaxy-celery-external@.service
      notify: daemon reload

    - name: Enable Celery internal
      systemd:
        name: "galaxy-celery-internal@{{ item }}.service"
        enabled: true
        state: restarted
      loop: "{{ range(0, galaxy_systemd_celery_internal_workers) | list }}"

    - name: Enable Celery external
      systemd:
        name: "galaxy-celery-external@{{ item }}.service"
        enabled: true
        state: restarted
      loop: "{{ range(0, galaxy_systemd_celery_external_workers) | list }}"
  when: not galaxy_systemd_watchdog | bool


- name: Deploy with watchdog
  block:
    - name: Disable normal internal
      systemd:
        name: "galaxy-celery-internal@{{ item }}.service"
        enabled: false
        state: stopped
      loop: "{{ range(0, galaxy_systemd_celery_internal_workers) | list }}"
      ignore_errors: true

    - name: Disable normal external
      systemd:
        name: "galaxy-celery-external@{{ item }}.service"
        enabled: false
        state: stopped
      loop: "{{ range(0, galaxy_systemd_celery_external_workers) | list }}"
      ignore_errors: true

    - name: Deploy Celery watchdog units for internal queue
      template:
        owner: root
        group: root
        mode: 0644
        src: galaxy-celery-dog-internal@.service.j2
        dest: /etc/systemd/system/galaxy-celery-dog-internal@.service
      notify: daemon reload

    - name: Deploy Celery watchdog units for external queue
      template:
        owner: root
        group: root
        mode: 0644
        src: galaxy-celery-dog-external@.service.j2
        dest: /etc/systemd/system/galaxy-celery-dog-external@.service
      notify: daemon reload


    - name: Enable Celery watchdog internal
      systemd:
        name: "galaxy-celery-dog-internal@{{ item }}.service"
        enabled: true
        state: restarted
      loop: "{{ range(0, galaxy_systemd_celery_internal_workers) | list }}"

    - name: Enable Celery watchdog external
      systemd:
        name: "galaxy-celery-dog-external@{{ item }}.service"
        enabled: true
        state: restarted
      loop: "{{ range(0, galaxy_systemd_celery_external_workers) | list }}"
  when: galaxy_systemd_watchdog | bool
